a = input('digite algo: ')
print('o valor primitivo dele é: ', type(a))
print('Só tem espaço?: ', a.isspace())
print('É tudo minúsculo?: ', a.islower())
print('É tudo maiúsculo?: ', a.isupper())
print('É um numero?: ', a.isnumeric())
print('É alfabético?: ', a.isalpha())
print('É alfanumérico?: ', a.isalnum())
print('É capitalizada?: ', a.istitle())
