numeroEscolhido = int(input('Digite um numero para a tabuada: '))

print('-' * 11) # efeito visual, ajuste pelo numero a quantidade de linhas
n1 = (numeroEscolhido * 1)
n2 = (numeroEscolhido * 2)
n3 = (numeroEscolhido * 3)
n4 = (numeroEscolhido * 4)
n5 = (numeroEscolhido * 5)
n6 = (numeroEscolhido * 6)
n7 = (numeroEscolhido * 7)
n8 = (numeroEscolhido * 8)
n9 = (numeroEscolhido * 9)
n10 = (numeroEscolhido * 10)

print('{} * 1 = {}'.format(numeroEscolhido, n1))
print('{} * 2 = {}'.format(numeroEscolhido, n2))
print('{} * 3 = {}'.format(numeroEscolhido, n3))
print('{} * 4 = {}'.format(numeroEscolhido, n4))
print('{} * 5 = {}'.format(numeroEscolhido, n5))
print('{} * 6 = {}'.format(numeroEscolhido, n6))
print('{} * 7 = {}'.format(numeroEscolhido, n7))
print('{} * 8 = {}'.format(numeroEscolhido, n8))
print('{} * 9 = {}'.format(numeroEscolhido, n9))
print('{} * 10 = {}'.format(numeroEscolhido, n10))
print('-' * 11) # efeito visual, ajuste pelo numero a quantidade de linhas
